### ISSUE TITLE
Doesn't work with anything remotely recent.

### ISSUE THREAD

**Issue by acidtonic** [zldrobit/onnx_tflite_yolov3#9]
Doesn't work.

Tensorflow older versions won't work with newer cuda 10.1 which I need for my own project.
New tensorflow lacks tf.contrib.slim and ridiculously expects everyone to just rewrite everything despite the fact I'm following a guide.
Now this requires tensorflow-addons, and that complains about tensorflow being too new.

To think I almost made this time.... What a sad state of affairs, terribly glad I live in C++ land.

Traceback (most recent call last):
  File "onnx2tf.py", line 13, in <module>
    file.write(output.graph.as_graph_def().SerializeToString())
AttributeError: 'NoneType' object has no attribute 'as_graph_def'

**Comment by zldrobit** [comment]
Would you like to use TF 2.x?
In this [PR](https://github.com/ultralytics/yolov5/pull/959), I wrote a newer version of code to convert Ultralytics Yolov5 to TF and TFLite models.

**Comment by zldrobit** [comment]
Close due to no recent activity. If you have further question, plz reopen it.
